clearbit_browser/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

companies/urls.py
from django.conf.urls import url

from .views import CompanyAddedView, CompanySearchView, CompanyDeleteView

urlpatterns = [
    url(r'^$', CompanyAddedView.as_view(), name='company_list'),
    url(r'^search/$', CompanySearchView.as_view(), name='company_search'),
    url(r'^delete/(?P<pk>\d+)$', CompanyDeleteView.as_view(), name='company_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, ListView
from django.views import defaults as default_views

from companies.views import CompanySearchView


urlpatterns = [
    url(r'^$',
        TemplateView.as_view(template_name='pages/home.html'),
        name='home'),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'),
        name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('clearbit_browser.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^companies/', include('companies.urls', namespace='companies')),

] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

clearbit_browser/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

companies/models.py
from __future__ import unicode_literals

from django.db import models

from clearbit_browser.users.models import User


class Company(models.Model):
    user = models.ForeignKey(User)
    clearbit_id = models.CharField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    description = models.TextField(null=True)
    updated_at = models.DateTimeField()
    logo_url = models.TextField(null=True)

companies/forms.py
from django import forms


class CompanySearchForm(forms.Form):
    search_query = forms.CharField(label='Company Domain', max_length=255)


class CompanyAddForm(forms.Form):
    clearbit_id = forms.CharField(label="Company ID", max_length=255)

clearbit_browser/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

companies/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.db import transaction, IntegrityError
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import ListView, View, DeleteView

from third_parties.clearbit_wrapper import ClearbitCompanySearch

from .models import Company
from .forms import CompanySearchForm, CompanyAddForm


@method_decorator(login_required, name='dispatch')
class CompanyAddedView(ListView):
    context_object_name = 'companies_list'
    template_name = 'companies/list.html'
    form_class = CompanyAddForm

    def get_queryset(self):
        return Company.objects.filter(user=self.request.user)

    def get(self, request):
        return render(request, self.template_name, {
            'company_list': self.get_queryset()
        })

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            clearbit_id = form.cleaned_data['clearbit_id']
            company = ClearbitCompanySearch().get_company(clearbit_id, hash_id=True)
            if company:
                try:
                    with transaction.atomic():
                        Company.objects.create(
                            description=company.description,
                            name=company.name,
                            clearbit_id=company.clearbit_id,
                            user=self.request.user,
                            updated_at=company.indexed_at,
                            logo_url=company.logo)
                        return render(request, self.template_name, {
                            'company_list': self.get_queryset()
                        })
                except IntegrityError:
                    messages.error(request,
                                   "You've added this company before.")
        else:
            messages.error(request, 'Invalid form. Please try again.')
        return render(request, self.template_name, {
            'company_list': self.get_queryset()
        })


@method_decorator(login_required, name='dispatch')
class CompanyDeleteView(DeleteView):
    model = Company
    success_url = reverse_lazy('companies:company_list')


class CompanySearchView(View):
    form_class = CompanySearchForm
    template_name = 'companies/search.html'
    context_object_name = 'company_list'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            query = form.cleaned_data['search_query']
            company = ClearbitCompanySearch().get_company(query, hash_id=False)
            if not company:
                messages.info(request, 'No companies found. Try again.')
            return render(request, self.template_name, {'form': form, 'company_details': company})
        else:
            messages.error(request, 'Invalid form. Please try again.')

        return render(request, self.template_name, {'form': form})

clearbit_browser/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

clearbit_browser/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}clearbit-browser{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">clearbit-browser</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 

clearbit_browser/templates/bootstrap4/field.html
{% load crispy_forms_field %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    {% if field|is_checkbox %}
        <div class="form-group{% if using_grid_layout %} row{% endif %}">
        {% if label_class %}
            <div class="controls col-{{ bootstrap_device_type }}-offset-{{ label_size }} {{ field_class }}">
        {% endif %}
    {% endif %}
    <{% if tag %}{{ tag }}{% else %}div{% endif %} id="div_{{ field.auto_id }}" {% if not field|is_checkbox %}class="form-group{% if using_grid_layout %} row{% endif %}{% else %}class="checkbox{% endif %}{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if form_show_errors%}{% if field.errors %} has-danger{% endif %}{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
        {% if field.label and not field|is_checkbox and form_show_labels %}
            <label for="{{ field.id_for_label }}" class="form-control-label {{ label_class }}{% if field.field.required %} requiredField{% endif %}">
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label>
        {% endif %}

        {% if field|is_checkboxselectmultiple %}
            {% include 'bootstrap4/layout/checkboxselectmultiple.html' %}
        {% endif %}

        {% if field|is_radioselect %}
            {% include 'bootstrap4/layout/radioselect.html' %}
        {% endif %}

        {% if not field|is_checkboxselectmultiple and not field|is_radioselect %}
            {% if field|is_checkbox and form_show_labels %}
                <label for="{{ field.id_for_label }}" class="{% if field.field.required %} requiredField{% endif %}">
                    {% crispy_field field %}
                    {{ field.label|safe }}
                    {% include 'bootstrap4/layout/help_text_and_errors.html' %}
                </label>
            {% else %}
                <div class="{{ field_class }}">
                    {% crispy_field field %}
                </div>
                {% include 'bootstrap4/layout/help_text_and_errors.html' %}
            {% endif %}
        {% endif %}
    </{% if tag %}{{ tag }}{% else %}div{% endif %}>
    {% if field|is_checkbox %}
        {% if label_class %}
            </div>
        {% endif %}
        </div>
    {% endif %}
{% endif %}

clearbit_browser/templates/bootstrap4/layout/field_errors_block.html
{% if form_show_errors and field.errors %}
    {% for error in field.errors %}
        <p id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="text-danger help-block">{{ error }}</p>
    {% endfor %}
{% endif %}

clearbit_browser/templates/companies/list.html
{% extends "base.html" %} 

{% block content %}
{% if company_list %}
<br/><p>List of companies you've added</p>
{% else %}
<p>Your companies list is empty.</p>
{% endif %}

<div class="container">
{% for company in company_list %}
<div class="jumbotron">
    <h1>{{ company.name }}
        <a href="https://{{ company.domain }}">
            <img src="{{ company.logo_url }}" height="42" width="42" />
        </a>
    </h1>
    <p>
        {% if company.linkedin_handle %}
        <a href="https://linkedin.com/{{ company.linkedin_handle }}">
            <img src="https://cdn1.iconfinder.com/data/icons/logotypes/32/square-linkedin-256.png" height="42" width="42" />
        </a> {% endif %} {% if company.facebook_handle %}
        <a href="https://facebook.com/{{ company.facebook_handle }}">
            <img src="http://icons.iconarchive.com/icons/danleech/simple/256/facebook-icon.png" height="42" width="42" />
        </a> {% endif %} {% if company.twitter_handle %}
        <a href="https://twitter.com/{{ company.twitter_handle }}">
            <img src="http://icons.iconarchive.com/icons/limav/flat-gradient-social/128/Twitter-icon.png" height="42" width="42" />
        </a> {% endif %}
    </p>
    <p>
        {{ company.description }}
        <br/> Last updated at: {{ company.updated_at|date:"D d M Y" }}
    </p>
    <p>
        {% if company.phone_numbers %}Phone numbers: {{ company.phone_numbers }} {% endif %}
        {% if company.email_addresses %}Email addresses: {{ company.email_addresses }} {% endif %}
        {% if company.phone %} Phone: {{ company.phone}} {% endif %}
    </p>
    <br/>
    <form id="company_delete" action={% url 'companies:company_delete' company.id %} method='post' accept-charset="utf-8">
        {% csrf_token %}
        <input type="hidden" name="clearbit_id" value="{{ company.clearbit_id }}">
        <button type='submit' class="btn btn-danger" id="company_id">Delete from list</button>
    </form>
</div>
{% endfor %}
</div>

{% endblock %}

clearbit_browser/templates/companies/search.html
{% extends "base.html" %} {% block content %} <br/> <p>Search for companies here (use domain such as "uber.com" for Uber)</p>

<form id="companysearch" action={% url 'companies:company_search' %} method='post' accept-charset="utf-8">
  {% csrf_token %}
  <input class="searchfield" id="searchbox" name="search_query" type="text" placeholder="Search">
<button class="btn btn-info" type="submit">
    <i class="fa fa-search">Search</i>
</button>
</form>

{% if company_details %}
<div class="container">
    <div class="jumbotron">
        <h1>{{ company_details.name }} <a href="https://{{ company_details.domain }}"><img src="{{ company_details.logo }}" height="42" width="42" /></a></h1>
        <p>
            {% if company_details.linkedin_handle %}
            <a href="https://linkedin.com/{{ company_details.linkedin_handle }}">
                <img src="https://cdn1.iconfinder.com/data/icons/logotypes/32/square-linkedin-256.png" height="42" width="42" />
            </a> {% endif %}
             {% if company_details.facebook_handle %}
            <a href="https://facebook.com/{{ company_details.facebook_handle }}">
                <img src="http://icons.iconarchive.com/icons/danleech/simple/256/facebook-icon.png" height="42" width="42" />
            </a> {% endif %}
             {% if company_details.twitter_handle %}
            <a href="https://twitter.com/{{ company_details.twitter_handle }}">
                <img src="http://icons.iconarchive.com/icons/limav/flat-gradient-social/128/Twitter-icon.png" height="42" width="42" />
            </a> {% endif %}
        </p>
        <p>
            {{ company_details.description }}
            <br/> Industry: {{ company_details.industry }}
            <br/> Tech stack: {% for tech in company_details.tech %}{{ tech }}{%if not forloop.last%},{%endif%} {% endfor %}
            <br/> Last updated at: {{ company_details.indexed_at|date:"D d M Y" }}
        </p>
        <p>
            {% if company_details.phone_numbers %}
             Phone numbers: {% for number in company_details.phone_numbers %}{{ number }}{%if not forloop.last%},{%endif%} {% endfor %}
            {% endif %} <br>
            {% if company_details.email_addresses %}
            Email addresses: {% for email in company_details.email_addresses %}{{ email }}{%if not forloop.last%},{%endif%} {% endfor %}
            {% endif %}
        </p>
        <br/>
        <form id="company_add" action={% url 'companies:company_list' %} method='post' accept-charset="utf-8">
             {% csrf_token %}
            <input type="hidden" name="clearbit_id" value="{{ company_details.clearbit_id }}">
            <button type='submit' class="btn btn-primary" id="company_id">Add to List</button>
        </form>
    </div>
</div>
{% endif %}
{% endblock content %}

clearbit_browser/templates/pages/about.html
{% extends "base.html" %}

{% block content %}
<br>
<div class="container">
<p>Search for companies using their domain name and add them to the list.</p>
</div>
{% endblock %}

clearbit_browser/templates/pages/home.html
{% extends "base.html" %} {% block content %}
<br/>
<p>
  <p>Search for companies here (use domain such as "uber.com" for Uber)</p>

  <form id="companysearch" action={% url 'companies:company_search' %} method='post' accept-charset="utf-8">
    {% csrf_token %}
    <input class="searchfield" id="searchbox" name="search_query" type="text" placeholder="Search">
    <button class="btn btn-info" type="submit">
      <i class="fa fa-search">Search</i>
    </button>
  </form>
</p>

{% endblock content %}

clearbit_browser/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
    <a class="btn btn-primary" href="{% url 'companies:company_list' %}" role="button">My Companies</a>
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

clearbit_browser/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

clearbit_browser/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}